### ISSUE TITLE
it builds - but then....

### ISSUE THREAD

**Issue by johndpope** [maartene/VisualNovel#3]
![IMG_2737](https://github.com/user-attachments/assets/c620c80e-9567-4ccf-a2a9-1c598dc738b3)

i do a clean 
build 
succeeds

but keeps bricking...

**Comment by johndpope** [comment]
maybe its a new inklecat problem

**Comment by maartene** [comment]
Thanks for taking the time to create an issue. I'm going to have a look.

**Comment by johndpope** [comment]
i fixed it - just older version - 
i also fixed audio manager
was missing font so ripped that out
it runs faster now 
see PR

**Comment by maartene** [comment]
OK. Awesome! Was just looking through the PR.

Note: I am going to update this package. I have a version of Ink for Swift now that includes the compiler, so it's no longer dependent on a local installation of Inklecate.
